SELECT CONCAT(NAME, '(', SUBSTRING(OCCUPATION, 1, 1), ')')
FROM OCCUPATIONS
ORDER BY NAME ASC;

SELECT
    CASE
        WHEN COUNT(*) <> 1 THEN CONCAT('There are a total of ', COUNT(*), ' ', LOWER(OCCUPATION), 's.')
        ELSE CONCAT('There is a total of ', COUNT(*), ' ', LOWER(OCCUPATION), '.')
    END
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(*), OCCUPATION ASC;